### ISSUE TITLE
Is there an rpm???

### ISSUE THREAD

**Issue by streki** [kanaka/libvncserver#4]
Hi,

I assume that there is few chances, but is there an existing rpm for this forked libvncserver.

By the way, I want to be sure to understood : by install this libvncserver version, it will improve my noVNC rendering??

Does the modifications done on libvncserver will be puted in the "official version" one day?

Thank you very much!!

**Comment by streki** [comment]
And another question (it can seem strange but...) :

This new libvncserver should be instaled on the server part or on the client part?

I ask because until now I thought the client needed it in order to be able to communicate with the server.
But wanting try the new version, I uninstaled my old libvncserver on my client, and ... noVNC is still working....

So I assume noVNC don't need libvncserver right???

I would be gratefull for some explanations...

**Comment by tenchman** [comment]
Yes, libvncserver has to be installed on the server side. If you do so and use a vnc server linked against libvncserver, you can connect directly to this server without the need of an websockets proxy.

noVNC is pure javascript on the client side and doesn't need libvncserver. noVNC requires a server which understands the websocket protocol or a proxy like websockify who sits between client and server.

**Comment by kanaka** [comment]
Streki, I don't about libvncserver RPMs. You might ask on the libvncserver mailing list if there are builds with these changes available somewhere. The WebSockets support is on the main development branch already, so distros that build and include libvncserver will eventually pick the changes up.

Using libvncserver may or may not improve your performance. It really depends on where your performance issues are coming from. From my own experience, using noVNC on recent versions of Chrome and connecting via websockify to a VNC server on the same LAN network, the performance feels almost native.

It's a bit dated, but I have older writeup about various issues related to performance on this wiki page: https://github.com/kanaka/novnc/wiki/Performance-notes In particular, read the "Network tuning" and "Video performance" section. It may help you identify where you performance issues are actually happening and work around them. Just as a specific example, if you are watching a video via noVNC without actually interacting with the mouse or keyboard, the performance will appear much worse than it actually is. The reason for this is because noVNC by default tries to limit frequency that it requests updates from the server. If you move the mouse during playback, the request rate will increase and the video will appear smoother (but note that the tradeoff is hugely increased bandwidth).

Also, if you are bandwidth constrained between the client and server, then that will seriously impact performance because VNC is fairly bandwidth intensive and doesn't support some of the compressed encodings yet. One way that libvncserver might help in that case is because libvncserver also contains a new VNC encoding (tightPNG) that is specifically optimized for clients like noVNC to limit bandwidth requirements.

**Comment by dscho** [comment]
Please note that @kanaka is not a maintainer of LibVNCServer I just added an official GitHub repository for the project: https://github.com/LibVNC/libvncserver. Please consider opening the pull request there.
