### ISSUE TITLE
compile or build  libvncserver for arm without buildroot

### ISSUE THREAD

**Issue by mohammadalnatour** [kanaka/libvncserver#9]
please i need your help how could i build the libvncserver in ARM without using the buildroot?

**Comment by kanaka** [comment]
Hi @mohammadalnatour, this is not the real libvncserver project. You want https://github.com/LibVNC/libvncserver

**Comment by mohammadalnatour** [comment]
@kanaka thank you very much but my question was i have an ARM embedded system and i want to compile the libvncserver in this ARM is there any way without using buildroot?
thank you

**Comment by kanaka** [comment]
@mohammadalnatour I have very little knowledge about libvncserver build issues and I haven't touched the code in years. You should really ask your question to the libvncserver project. This is just an old copy of the code. The only reason github doesn't show it as a fork is because I copied it before it was moved from sourceforce to github.

**Comment by mohammadalnatour** [comment]
@kanaka Ok Thank you very much
